"""create complaints table

Revision ID: 1be049cfc142
Revises: 
Create Date: 2026-09-26 19:40:28.925641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be049cfc142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('reporter_contact', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('water', 'electricity', 'sanitation', 'roads', 'streetlights', 'other', name='category'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'rejected', name='status'), nullable=False),
    sa.Column('ai_summary', sa.String(length=140), nullable=True),
    sa.Column('triaged_by', sa.String(), nullable=True),
    sa.Column('triage_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    # ### end Alembic commands ###
