apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/humnaattique4-sys/civicpulse-backend
    newTag: dev
  - name: ghcr.io/humnaattique4-sys/civicpulse-frontend
    newTag: dev